// Code generated by "codegen -type=int /root/go/src/eazycloud/internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to errors package
func init() {
	register(ErrSuccess, 200, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrUnknown, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrBind, 400, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrValidation, 400, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrTokenInvalid, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrPageNotFound, 404, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrOperationBatchExecute, 200, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrDatabase, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrEncrypt, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrSignatureInvalid, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrExpired, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrInvalidAuthHeader, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrMissingHeader, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrPasswordIncorrect, 401, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrPermissionDenied, 403, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrEncodingFailed, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrDecodingFailed, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrInvalidJSON, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrEncodingJSON, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrDecodingJSON, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrInvalidYaml, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrEncodingYaml, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrDecodingYaml, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrHTTPError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrHTTPResponseDataParseError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrHTTPClientGenerateError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrGRPCClientGenerateError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrGRPCClientCertificateError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrGRPCClientDialError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrGRPCClientInvokeServiceError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrGRPCResponseDataParseError, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
	register(ErrUserNotFound, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
}
