// Code generated by sort-gen; DO NOT EDIT.

package iapiserver

// 此文件包含自动生成的 SortFields 方法

// SortFields 返回结构体 MonitoringNamespaceListResponse 中所有基本可比较类型字段的路径映射
// 此方法由代码生成器自动生成，请勿手动修改
func (m MonitoringNamespaceListResponse) SortFields() map[string]struct{} {
	return map[string]struct{}{
		"total_count": {},
	}
}

// SortFields 返回结构体 MonitorDataResponse 中所有基本可比较类型字段的路径映射
// 此方法由代码生成器自动生成，请勿手动修改
func (m MonitorDataResponse) SortFields() map[string]struct{} {
	return map[string]struct{}{
		"namespace":     {},
		"name":          {},
		"addr":          {},
		"type":          {},
		"cpu":           {},
		"cpu_used":      {},
		"cpu_total":     {},
		"memory":        {},
		"memory_used":   {},
		"memory_total":  {},
		"disk_ratio":    {},
		"disk_used":     {},
		"disk_total":    {},
		"disk_read":     {},
		"disk_write":    {},
		"pod_ratio":     {},
		"pod_count":     {},
		"pod_total":     {},
		"network_read":  {},
		"network_write": {},
	}
}

// SortFields 返回结构体 PodInfo 中所有基本可比较类型字段的路径映射
// 此方法由代码生成器自动生成，请勿手动修改
func (p PodInfo) SortFields() map[string]struct{} {
	return map[string]struct{}{
		"resource":                    {},
		"resource_request":            {},
		"resource_limit":              {},
		"pod_status.status":           {},
		"pod_status.message":          {},
		"pod_status.reason":           {},
		"pod_status.ready_containers": {},
		"pod_status.total_containers": {},
		"max_restarts":                {},
		"controller.object_meta":      {},
		"controller.type_meta":        {},
		"node_info":                   {},
		"cluster.type":                {},
		"cluster.is_stop":             {},
		"cluster.config":              {},
		"cluster.state":               {},
		"cluster.IsManaged":           {},
		"cluster.state_desc":          {},
		"cluster.IsHighAvailable":     {},
		"cluster.cluster_node_scale":  {},
		"cluster.ServicePodCidr":      {},
		"cluster.PodCidr":             {},
	}
}
