//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package tls

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratableKeyCert) DeepCopyInto(out *GeneratableKeyCert) {
	*out = *in
	out.CertData = in.CertData
	out.CertKey = in.CertKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratableKeyCert.
func (in *GeneratableKeyCert) DeepCopy() *GeneratableKeyCert {
	if in == nil {
		return nil
	}
	out := new(GeneratableKeyCert)
	in.DeepCopyInto(out)
	return out
}
