# example-server 全配置

# 通用服务配置
server:
  mode: debug # server mode: release, debug, test，默认 release
  healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
  middlewares: context,requestid # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
  runtime-debug: true # 启动运行时调试, 可通过Linux信号触发进行程序性能采集等。
  runtime-debug-dir: ${EXAMPLE_SERVER_RUNTIME_DEBUG_OUTPUT_DIR} #运行时调试时采集的数据存放目录

# HTTP 配置
insecure:
  bind-address: ${EXAMPLE_SERVER_INSECURE_BIND_ADDRESS} # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
  bind-port: ${EXAMPLE_SERVER_INSECURE_BIND_PORT} # 提供非安全认证的监听端口，默认为 8080
  required: true

# HTTPS 配置
secure:
  bind-address: ${EXAMPLE_SERVER_SECURE_BIND_ADDRESS} # HTTPS 安全模式的 IP 地址，默认为 0.0.0.0
  bind-port: ${EXAMPLE_SERVER_SECURE_BIND_PORT} # 使用 HTTPS 安全模式的端口号默认为 8443
  required: false
  tls:
    #cert-dir:  # TLS 证书所在的目录
    #pair-name:  # TLS 私钥对名称
    cert-key:
      cert-file: ${EXAMPLE_SERVER_SECURE_TLS_CERT_FILE} # 包含 x509 证书的文件路径，用 HTTPS 认证
      private-key-file: ${EXAMPLE_SERVER_SECURE_TLS_CERT_KEY} # TLS 私钥

# JWT 配置
jwt:
  realm: JWT # jwt 标识
  key: dfVpOK8LZeJLZHYmHdb1VdyRrACKpqoo # 服务端密钥
  timeout: 24h # token 过期时间(小时)
  max-refresh: 24h # token 更新时间(小时)

log:
  name: example-server # Logger的名字
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths: ${EAZYCLOUD_LOG_DIR}/example-server.log,stdout # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件。
  error-output-paths: ${EAZYCLOUD_LOG_DIR}/example-server.error.log # zap内部(非业务)错误日志输出路径，多个输出，逗号分开

feature:
  enable-metrics: true # 开启 metrics, router:  /metrics
  profiling: true # 开启性能分析,查看程序栈、线程等系统信息,默认值为true
  profile_address: 127.0.0.0:6060 # 独立服务地址
  standalone_profiling: false # 非独立服务时,可以通过 <host>:<port>/debug/pprof/地址.独立服务通过<profile_address>/debug/pprof/地址查看.默认值为false

